apiVersion: v1
kind: Secret
metadata:
  name: cocoplanner-secrets
type: Opaque
data:
  # Note: Values should be base64 encoded
  serper-api-key: BASE64_ENCODED_VALUE
  openai-api-key: BASE64_ENCODED_VALUE
  email-sender: BASE64_ENCODED_VALUE
  email-password: BASE64_ENCODED_VALUE
  amadeus-api-key: BASE64_ENCODED_VALUE
  amadeus-api-secret: BASE64_ENCODED_VALUE
  mongodb-atlas-uri: BASE64_ENCODED_VALUE